const $=id=>document.getElementById(id);
const state={research:null,examples:[],selected:null,view:null,prediction:null,window:0,enabled:new Set(Array.from({length:18},(_,i)=>i)),request:0};
async function api(path,options){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'The research service is unavailable.');return body;}
function status(text,kind=''){ $('status-text').textContent=text;$('status').className=`status ${kind}`;}
function metric(value){return value==null?'—':value.toFixed(3);}
function draw(){EEGPlot.waveform($('waveform'),state.view,state.enabled,state.prediction);EEGPlot.timeline($('timeline'),state.prediction,state.window,state.view?.example.seizures||[]);}
function resultTable(title,rows,columns){
  const wrap=document.createElement('div');wrap.className='table-scroll';wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',title);
  const table=document.createElement('table'),caption=document.createElement('caption');caption.textContent=title;table.append(caption);
  const head=document.createElement('thead'),tr=document.createElement('tr');for(const [,label] of columns){const th=document.createElement('th');th.scope='col';th.textContent=label;tr.append(th);}head.append(tr);table.append(head);
  const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const [key] of columns){const td=document.createElement('td'),value=row[key];td.textContent=value==null?'—':typeof value==='number'?(['n_windows','positive_windows','tn','fp','fn','tp'].includes(key)?value.toLocaleString():value.toFixed(3)):value;tr.append(td);}body.append(tr);}table.append(body);wrap.append(table);return wrap;
}
function showMetrics(){
  const model=state.research.models[$('model').value];if(!model)return;const report=model.metrics;
  for(const key of ['sensitivity','specificity','f1','auprc_ap'])$(key).textContent=metric(report.pooled[key]);
  $('metrics-caption').textContent=`Held-out test · ${report.patients.length} unseen individuals · ${report.pooled.n_windows.toLocaleString()} windows · Pooled window metrics; patient and case results below.`;
  $('result-details').hidden=false;
  $('result-context').textContent=`${report.pooled.positive_windows.toLocaleString()} positive windows · ${(report.pooled.prevalence*100).toFixed(4)}% prevalence · ${report.pooled.duration_hours.toFixed(2)} hours. All eligible test windows retained. Patient macro gives equal weight to each individual; chb01 + chb21 are grouped. AP means average precision. Undefined metrics appear as —. Baseline remains the validation-selected default.`;
  const metrics=[['accuracy','Accuracy'],['sensitivity','Sensitivity'],['specificity','Specificity'],['precision','Precision'],['f1','F1'],['auroc','AUROC'],['auprc_ap','AP']];
  const counts=[['n_windows','Windows'],['positive_windows','Positive'],['tn','TN'],['fp','FP'],['fn','FN'],['tp','TP']];
  $('result-tables').replaceChildren(resultTable('Pooled and patient-macro results',[{scope:'Pooled',...report.pooled},{scope:'Patient macro',...report.patient_macro}],[['scope','Scope'],...metrics]),resultTable('Canonical individuals',report.patients,[['individual_id','Individual'],...counts,...metrics]),resultTable('Case breakdown',report.cases,[['case_id','Case'],...counts,...metrics]));
}
function curatedCategory(example){return example.curations?.[$('model').value] || (example.curation_model===$('model').value?example.curation_category:null);}
function renderExamples(){const category=$('category').value;$('examples').replaceChildren();const selected=state.examples.filter(e=>curatedCategory(e)&&(category==='all'||curatedCategory(e)===category));for(const example of selected){const button=document.createElement('button');button.className=`example-button ${state.selected===example.id?'active':''}`;const badge=document.createElement('span');badge.className=`outcome ${curatedCategory(example).startsWith('F')?'failure':''}`;badge.textContent=curatedCategory(example);const title=document.createElement('strong');title.textContent=`${example.case_id.toUpperCase()} · ${example.focus_start_seconds}s`;const detail=document.createElement('span');detail.textContent=example.recording.split('/')[1];button.append(badge,title,detail);button.onclick=()=>selectExample(example.id);$('examples').append(button);}if(!selected.length){const p=document.createElement('p');p.className='help';p.textContent='No examples in this category. No examples have been fabricated.';$('examples').append(p);}}
function clearReadout(){state.view=null;state.prediction=null;$('prediction').textContent='No example selected';$('truth').textContent='Annotated label: —';$('score').textContent='—';$('threshold').textContent='Frozen validation threshold';$('recording').textContent='Select an example';$('individual').textContent='—';$('case').textContent='—';$('source-hash').textContent='—';$('source-link').hidden=true;$('view-range').textContent='—';$('patient-context').textContent='';$('previous').disabled=true;$('next').disabled=true;$('waveform-empty').hidden=false;draw();}
async function selectExample(id){const token=++state.request;state.selected=id;clearReadout();renderExamples();status('Loading EEG and running the selected model…');try{const [view,prediction]=await Promise.all([api(`/api/examples/${encodeURIComponent(id)}`),api('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({example_id:id,model_id:$('model').value})})]);if(token!==state.request)return;state.view=view;state.prediction=prediction;state.window=Math.max(0,prediction.windows.findIndex(w=>w.start_seconds===view.example.focus_start_seconds));$('waveform-empty').hidden=true;$('recording').textContent=view.example.recording;$('individual').textContent=view.example.individual_id;$('case').textContent=view.example.case_id;$('source-hash').textContent=view.example.source_sha256;$('source-link').href=view.example.source_url;$('source-link').hidden=false;$('patient-context').textContent='This individual was not used for training or validation. This clip was curated after the final evaluation.';updateWindow();status('Verified held-out example · real model inference · uncalibrated seizure scores','ready');}catch(error){if(token===state.request)status(error.message,'error');}}
function updateWindow(){const w=state.prediction?.windows[state.window];if(!w)return;$('prediction').textContent=w.predicted_label?'Seizure-positive window':'Non-seizure window';$('truth').textContent=`Annotated label: ${w.true_label?'seizure':'non-seizure'} · ${w.start_seconds}–${w.end_seconds}s`;$('score').textContent=w.score.toFixed(3);$('threshold').textContent=`Fixed validation threshold ${state.prediction.threshold.toFixed(3)}`;$('view-range').textContent=`${state.view.view_start_seconds.toFixed(1)}–${(state.view.view_start_seconds+state.view.signal_uv[0].length/256).toFixed(1)}s · shared display gain`;$('previous').disabled=state.window===0;$('next').disabled=state.window===state.prediction.windows.length-1;draw();}
async function navigateWindow(index){if(!state.prediction)return;state.window=Math.max(0,Math.min(index,state.prediction.windows.length-1));const token=++state.request;try{const view=await api(`/api/examples/${encodeURIComponent(state.selected)}?start_seconds=${state.prediction.windows[state.window].start_seconds-4}`);if(token!==state.request)return;state.view=view;updateWindow();}catch(error){status(error.message,'error');}}
$('previous').onclick=()=>navigateWindow(state.window-1);$('next').onclick=()=>navigateWindow(state.window+1);
$('timeline').onclick=event=>{if(!state.prediction)return;const rect=$('timeline').getBoundingClientRect(),fraction=(event.clientX-rect.left-32)/(rect.width-44);navigateWindow(Math.floor(fraction*state.prediction.windows.length));};
$('channels-toggle').onclick=()=>{const open=$('channel-options').hidden;$('channel-options').hidden=!open;$('channels-toggle').setAttribute('aria-expanded',String(open));};
function selectCurated(){renderExamples();const category=$('category').value;const eligible=state.examples.filter(e=>curatedCategory(e)&&(category==='all'||curatedCategory(e)===category));const selected=eligible.find(e=>e.id===state.selected)||eligible[0];if(selected)selectExample(selected.id);else{++state.request;state.selected=null;clearReadout();status('No examples were curated in this category for this model.','error');}}
$('category').onchange=selectCurated;$('model').onchange=()=>{showMetrics();selectCurated();};
new ResizeObserver(draw).observe($('waveform'));
async function boot(){try{state.research=await api('/api/research');for(const [i,name] of state.research.channels.entries()){const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.onchange=()=>{checkbox.checked?state.enabled.add(i):state.enabled.delete(i);$('channels-toggle').querySelector('span').textContent=state.enabled.size;draw();};label.append(checkbox,document.createTextNode(name));$('channel-options').append(label);}if(state.research.status!=='ready'){status('Experiment pending · model artifacts are not yet available. No research metrics are displayed.');draw();return;}$('model').replaceChildren();for(const name of Object.keys(state.research.models)){const option=document.createElement('option');option.value=name;option.textContent=name==='baseline'?'V1-style CNN baseline':'Compact residual CNN';$('model').append(option);}$('model').value=state.research.default_model;$('model').disabled=false;$('category').disabled=false;state.examples=(await api('/api/examples')).examples;showMetrics();selectCurated();}catch(error){status(error.message,'error');}}
boot();
