const $=id=>document.getElementById(id);
const state={research:null,examples:[],selected:null,view:null,prediction:null,window:0,enabled:new Set(Array.from({length:18},(_,i)=>i)),request:0};
async function api(path,options){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'The research service is unavailable.');return body;}
function status(text,kind=''){ $('status-text').textContent=text;$('status').className=`status ${kind}`;}
function metric(value){return value==null?'—':value.toFixed(3);}
function draw(){EEGPlot.waveform($('waveform'),state.view,state.enabled,state.prediction);EEGPlot.timeline($('timeline'),state.prediction,state.window,state.view?.example.seizures||[]);}
function showMetrics(){const model=state.research.models[$('model').value];if(!model)return;for(const key of ['sensitivity','specificity','f1','auprc_ap'])$(key).textContent=metric(model.metrics.pooled[key]);$('metrics-caption').textContent=`Held-out test · ${model.metrics.patients.length} unseen individuals · ${model.metrics.pooled.n_windows.toLocaleString()} windows · Pooled window metrics; per-patient results in the repository.`;}
function renderExamples(){const category=$('category').value;$('examples').replaceChildren();const selected=state.examples.filter(e=>category==='all'||e.curation_category===category);for(const example of selected){const button=document.createElement('button');button.className=`example-button ${state.selected===example.id?'active':''}`;const badge=document.createElement('span');badge.className=`outcome ${example.curation_category.startsWith('F')?'failure':''}`;badge.textContent=example.curation_category;const title=document.createElement('strong');title.textContent=`${example.case_id.toUpperCase()} · ${example.focus_start_seconds}s`;const detail=document.createElement('span');detail.textContent=example.recording.split('/')[1];button.append(badge,title,detail);button.onclick=()=>selectExample(example.id);$('examples').append(button);}if(!selected.length){const p=document.createElement('p');p.className='help';p.textContent='No examples in this category. No examples have been fabricated.';$('examples').append(p);}}
async function selectExample(id){const token=++state.request;state.selected=id;state.view=null;state.prediction=null;draw();$('waveform-empty').hidden=false;renderExamples();status('Loading EEG and running the selected model…');try{const [view,prediction]=await Promise.all([api(`/api/examples/${encodeURIComponent(id)}`),api('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({example_id:id,model_id:$('model').value})})]);if(token!==state.request)return;state.view=view;state.prediction=prediction;state.window=Math.max(0,prediction.windows.findIndex(w=>w.start_seconds===view.example.focus_start_seconds));$('waveform-empty').hidden=true;$('recording').textContent=view.example.recording;$('individual').textContent=view.example.individual_id;$('patient-context').textContent='This individual was not used for training or validation. This clip was curated after the final evaluation.';updateWindow();status('Verified held-out example · real model inference · uncalibrated seizure scores','ready');}catch(error){if(token===state.request)status(error.message,'error');}}
function updateWindow(){const w=state.prediction?.windows[state.window];if(!w)return;$('prediction').textContent=w.predicted_label?'Seizure detected':'Non-seizure';$('truth').textContent=`Annotated label: ${w.true_label?'seizure':'non-seizure'} · ${w.start_seconds}–${w.end_seconds}s`;$('score').textContent=w.score.toFixed(3);$('threshold').textContent=`Fixed validation threshold ${state.prediction.threshold.toFixed(3)}`;$('view-range').textContent=`${state.view.view_start_seconds.toFixed(1)}–${(state.view.view_start_seconds+state.view.signal_uv[0].length/256).toFixed(1)}s · shared display gain`;$('previous').disabled=state.window===0;$('next').disabled=state.window===state.prediction.windows.length-1;draw();}
async function navigateWindow(index){if(!state.prediction)return;state.window=Math.max(0,Math.min(index,state.prediction.windows.length-1));const token=++state.request;try{const view=await api(`/api/examples/${encodeURIComponent(state.selected)}?start_seconds=${state.prediction.windows[state.window].start_seconds-4}`);if(token!==state.request)return;state.view=view;updateWindow();}catch(error){status(error.message,'error');}}
$('previous').onclick=()=>navigateWindow(state.window-1);$('next').onclick=()=>navigateWindow(state.window+1);
$('timeline').onclick=event=>{if(!state.prediction)return;const rect=$('timeline').getBoundingClientRect(),fraction=(event.clientX-rect.left-32)/(rect.width-44);navigateWindow(Math.floor(fraction*state.prediction.windows.length));};
$('channels-toggle').onclick=()=>{const open=$('channel-options').hidden;$('channel-options').hidden=!open;$('channels-toggle').setAttribute('aria-expanded',String(open));};
$('category').onchange=renderExamples;$('model').onchange=()=>{showMetrics();if(state.selected)selectExample(state.selected);};
new ResizeObserver(draw).observe($('waveform'));
async function boot(){try{state.research=await api('/api/research');for(const [i,name] of state.research.channels.entries()){const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.onchange=()=>{checkbox.checked?state.enabled.add(i):state.enabled.delete(i);$('channels-toggle').querySelector('span').textContent=state.enabled.size;draw();};label.append(checkbox,document.createTextNode(name));$('channel-options').append(label);}if(state.research.status!=='ready'){status('Experiment pending · model artifacts are not yet available. No research metrics are displayed.');draw();return;}$('model').replaceChildren();for(const name of Object.keys(state.research.models)){const option=document.createElement('option');option.value=name;option.textContent=name==='baseline'?'V1-style CNN baseline':'Compact residual CNN';$('model').append(option);}$('model').value=state.research.default_model;$('model').disabled=false;$('category').disabled=false;state.examples=(await api('/api/examples')).examples;showMetrics();renderExamples();if(state.examples.length)await selectExample(state.examples[0].id);else status('No curated examples are available.','error');}catch(error){status(error.message,'error');}}
boot();
